language: cpp
os: linux
dist: bionic
compiler:
  - g++-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7

install:
  - sudo bash nautilus-install.sh --no-build

script:
  - sudo bash nautilus-install.sh

notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always