language: cpp
os: linux
dist: bionic
compiler:
  - g++-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7

install:
  - sudo apt-get update -y && sudo apt-get install wget -y && sudo rm -r ./* && wget raw.githubusercontent.com/D3PSI/nautilus/master/nautilus-install.sh && sudo bash nautilus-install.sh --no-build

script: 
  - sudo bash nautilus-install.sh

notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always