version: 1.0.{build}
image:
- Ubuntu
- Ubuntu1804
- Visual Studio 2019
- Visual Studio 2017
platform: x64
configuration: Release
skip_tags: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
    - sh: sudo bash nautilus-install.sh --no-build
    build_script:
    - sh: sudo bash nautilus-install.sh
    after_build:
    - sh: zip -j nautilus-linux-rolling.zip nautilus/libnautilus.a
    artifacts:
      - path: nautilus-linux-rolling.zip
        name: libnautilus-linux
  -
    matrix:
      only:
        - image: Ubuntu1804
    install:
    - sh: sudo bash nautilus-install.sh --no-build
    build_script:
    - sh: sudo bash nautilus-install.sh
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      VULKAN_SDK: C:/VulkanSDK/1.1.114.0
    cache:
      - VulkanSDK.exe
    install:
      - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
      - VulkanSDK.exe /S
      - git submodule update --init --recursive
    before_build:
      - ps: .\get_linux_artifact_appveyor.ps1
      - cmake -G "Visual Studio 16 2019" .
    build:
      project: NAUTILUS_EXAMPLES.sln
      parallel: true
    after_build:
      - 7z a nautilus-win-rolling-%APPVEYOR_BUILD_VERSION%.zip C:/projects/nautilus/nautilus/Release/nautilus.lib
    artifacts:
      - path: nautilus-win-rolling-$(appveyor_build_version).zip
        name: libnautilus-win
      - path: nautilus-linux-rolling-$(appveyor_build_version).zip
        name: libnautilus-linux
    deploy:
      tag: $(appveyor_build_version)-r
      release: nautilus-rolling-$(appveyor_build_version)
      description: Rolling channel for releases of nautilus compiled libraries
      provider: GitHub
      auth_token:
        secure: otHmBJW4rJT8ONsToA2oc13ybNJR1oktyFX8tHeoJ/97fX570JRnUbrG3ubRrbFi
      artifact: libnautilus-linux, libnautilus-win
      draft: false
      prerelease: false
      on:
        branch: master
  -
    matrix:
      only:
        - image: Visual Studio 2017
    environment:
      VULKAN_SDK: C:/VulkanSDK/1.1.114.0
    cache:
      - VulkanSDK.exe
    install:
      - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
      - VulkanSDK.exe /S
      - git submodule update --init --recursive
    before_build:
      - cmake -G "Visual Studio 15 2017 Win64" .
    build:
      project: NAUTILUS_EXAMPLES.sln
      parallel: true