version: 1.0.{build}
image:
- Ubuntu
- macos
- Visual Studio 2019
- Ubuntu1804
- Visual Studio 2017
- macos
platform: x64
configuration: Release
skip_tags: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
    - sh: sudo bash nautilus-install.sh --no-build
    build_script:
    - sh: sudo bash nautilus-install.sh --ci
    after_build:
    - sh: mkdir libs && mv nautilus/libnautilus.a libs/ && rm -rfv examples/ && mkdir examples && mkdir examples/res && cp -r res/* examples/res && cp -r bin/* examples/ && zip -r nautilus-linux-rolling.zip libs/ include/ examples/
    artifacts:
      - path: nautilus-linux-rolling.zip
        name: libnautilus-linux
  -
    matrix:
      only:
        - image: Ubuntu1804
    install:
    - sh: sudo apt-get update -y && sudo apt-get -y install git cmake make gcc-8 g++-8 libxinerama-dev libxcursor-dev libxrandr-dev libx11-dev libxi-dev libegl1-mesa-dev && export CC=gcc-8 && export CXX=g++-8 && git submodule sync && git submodule update --init --recursive
    build_script:
    - sh: cmake CMakeLists.txt && make -j2
  -
    matrix:
      only:
        - image: macos
    cache: 
      - VulkanSDK.tar.gz
    install:
    - sh: git submodule sync && git submodule update --init --recursive
    - sh: curl -L --silent --show-error --output VulkanSDK.tar.gz https://vulkan.lunarg.com/sdk/download/1.1.114.0/mac/vulkansdk-macos-1.1.114.0.tar.gz?Human=true
    - sh: tar -xzf VulkanSDK.tar.gz
    - sh: cd vulkansdk-macos-1.1.114.0/ && ./install_vulkan.py --force-install && cd ..
    build_script:
    - sh: cmake CMakeLists.txt && make -j2
    after_build:
    - sh: mkdir libs && mv nautilus/libnautilus.a libs/ && rm -rfv examples/ && mkdir examples && mkdir examples/res && cp -r res/* examples/res && cp -r bin/* examples/ && cp -r lib/*.dylib examples/ && cp -r lib/*.dylib libs/ && zip -r nautilus-macos-rolling.zip libs/ include/ examples/
    artifacts:
      - path: nautilus-macos-rolling.zip
        name: libnautilus-macos
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      VULKAN_SDK: C:/VulkanSDK/1.1.114.0
    cache:
      - VulkanSDK.exe
    install:
      - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
      - VulkanSDK.exe /S
      - git submodule update --init --recursive
    before_build:
      - ps: .\get_build_artifacts_appveyor.ps1
      - cmake -G "Visual Studio 16 2019" -S . -B build/
    build:
      project: build/NAUTILUS_EXAMPLES.sln
      parallel: true
    after_build:
      - mkdir C:\projects\nautilus\libs
      - move C:\projects\nautilus\build\nautilus\Release\nautilus.lib C:\projects\nautilus\libs
      - rmdir /s /q C:\projects\nautilus\examples 
      - if not exist C:\projects\nautilus\examples mkdir C:\projects\nautilus\examples 
      - xcopy /e /v C:\projects\nautilus\res C:\projects\nautilus\examples\res\ 
      - copy C:\projects\nautilus\build\ext\glfw\src\Release\glfw3.dll C:\projects\nautilus\examples\
      - xcopy C:\projects\nautilus\build\bin\Release C:\projects\nautilus\examples\ 
      - 7z a nautilus-win-rolling-%APPVEYOR_BUILD_VERSION%.zip libs/ include/ examples/
    artifacts:
      - path: nautilus-win-rolling-$(appveyor_build_version).zip
        name: libnautilus-win
      - path: nautilus-linux-rolling-$(appveyor_build_version).zip
        name: libnautilus-linux
      - path: nautilus-macos-rolling-$(appveyor_build_version).zip
        name: libnautilus-macos
    deploy:
      tag: r$(appveyor_build_version)
      release: nautilus-rolling-$(appveyor_build_version)
      description: Rolling channel for releases of nautilus compiled libraries --- $(APPVEYOR_REPO_COMMIT_MESSAGE)
      provider: GitHub
      auth_token:
        secure: otHmBJW4rJT8ONsToA2oc13ybNJR1oktyFX8tHeoJ/97fX570JRnUbrG3ubRrbFi
      artifact: libnautilus-linux, libnautilus-win, libnautilus-macos
      draft: false
      prerelease: false
      on:
        branch: master
  -
    matrix:
      only:
        - image: Visual Studio 2017
    environment:
      VULKAN_SDK: C:/VulkanSDK/1.1.114.0
    cache:
      - VulkanSDK.exe
    install:
      - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
      - VulkanSDK.exe /S
      - git submodule update --init --recursive
    before_build:
      - cmake -G "Visual Studio 15 2017 Win64" .
    build:
      project: NAUTILUS_EXAMPLES.sln
      parallel: true
  -
    matrix:
      only:
        - image: macos
    cache: 
      - VulkanSDK.tar.gz
    install:
    - sh: bash nautilus-install.sh --no-build
    - sh: curl -L --silent --show-error --output VulkanSDK.tar.gz https://vulkan.lunarg.com/sdk/download/1.1.114.0/mac/vulkansdk-macos-1.1.114.0.tar.gz?Human=true
    - sh: tar -xzf VulkanSDK.tar.gz
    - sh: cd vulkansdk-macos-1.1.114.0/ && ./install_vulkan.py --force-install && cd ..
    build_script:
    - sh: bash nautilus-install.sh --ci