version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -y && apt-get install wget -y && rm -r ./* && wget raw.githubusercontent.com/D3PSI/nautilus/master/nautilus-install.sh && bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: bash nautilus-install.sh