version: 2.1

jobs:
  "Debian Latest":
    docker:
      - image: debian
    steps:
      - checkout
      - run:
          name: Install dependencies	
          command: bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: bash nautilus-install.sh --ci
  "Fedora Latest":
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: Install dependencies	
          command: bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: bash nautilus-install.sh
  "CentOS Latest":
    docker:
      - image: centos
    steps:
      - checkout
      - run:
          name: Install dependencies	
          command: bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: bash nautilus-install.sh
  "OpenSUSE Tumbleweed Latest":
    docker:
      - image: opensuse/tumbleweed
    steps:
      - checkout
      - run:
          name: Install dependencies	
          command: bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: bash nautilus-install.sh
workflows:
  version: 2.1
  build:
    jobs:
      - "Debian Latest"
      - "Fedora Latest"
      - "CentOS Latest"