version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule sync --recursive && git submodule update --init --recursive
      - run:
          name: Install dependencies	
          command: sudo bash nautilus-install.sh --no-build
      - run:
          name: Build
          command: sudo bash nautilus-install.sh